<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Data Mining</b></center>
<center><b><h1>Lab - 7 (Part 2)</b></center>    
<pre>

### Step 1: Load the Dataset
Load the `Tdata.csv` file and display the first few rows.

In [1]:
import  pandas as pd
import numpy as np


data = pd.read_csv('Tdata.csv')

data

  Transaction  bread  butter  coffee  eggs  jam  milk
0          T1      1       1       0     0    0     1
1          T2      1       1       0     0    1     0
2          T3      1       0       0     1    0     1
3          T4      1       1       0     0    0     1
4          T5      1       0       1     0    0     0
5          T6      0       0       1     1    1     0

### Step 2: Drop the 'Transaction' Column
We're only interested in the items (not the transaction IDs).

In [2]:
data = data.drop('Transaction',axis=1)

### Step 3: Count Single Items
See how many transactions include each item.

In [3]:
data.sum()

bread     5
butter    3
coffee    2
eggs      2
jam       2
milk      3
dtype: int64

### Step 4: Define Apriori Function
This function finds frequent itemsets of size 1, 2, and 3 with minimum support.

In [14]:
from itertools import combinations

# find_frequant_itemset(data,2)

def find_frequant_itemset(df,minSupport):
    n = len(df)
    result = []

    for k in [1,2,3] :
        for items in combinations(df.columns,k) :
            mask = df[list(items)].all(axis = 1)
            support = mask.sum() / n

            # print(f"{frozenset(items)} -> {round(support,2)}")

            if support >= minSupport:
                result.append((frozenset(items),round(support,2)))
    
    return result


find_frequant_itemset(data,2)

[]

### Step 5: Run Apriori
Set `min_support = 0.6` and display the frequent itemsets.

In [ ]:
itemsets = find_frequant_itemset(data,minSupport= 0.6)


for i,support in itemsets:
    print(f'{set(i)} - > support {support}')

{'bread'} - > support 0.83

### Step 6 Display as a DataFrame

In [19]:
resultData = pd.DataFrame(itemsets,columns=['itemsets','support'])
resultData

  itemsets  support
0  (bread)     0.83

# Orange Tool : - >Generate Same Frequent Patterns in Orange tools

# Extra : - >  Define Apriori Function without itertools