# 🧺 Online Retail Dataset (Apriori Preprocessing) - TASK 2
**Dataset**: https://www.kaggle.com/datasets/vijayuv/onlineretail

# Step 1: Load Data

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('OnlineRetail1.csv',encoding='latin')

secondData = data.copy()
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

# Step 2: Drop Missing Invoices or Descriptions

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [5]:
data = data.dropna(how='any',subset=['Description'])
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

# Step 3: Remove Canceled Invoices <BR> Start with letter 'c'

In [6]:
data = data[~data['InvoiceNo'].str.startswith('C')]
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

# Step 4: Keep Only Positive Quantities

In [7]:
data = data[data['Quantity'] > 0]
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

# Step 5: Standardize Item Descriptions | Lower case and remove space

In [8]:
data['Description'] = data['Description'].str.lower().str.replace(' ','')
data

C:\Users\mannm\AppData\Local\Temp\ipykernel_2476\2779058024.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Description'] = data['Description'].str.lower().str.replace(' ','')

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,whitehangingheartt-lightholder,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,whitemetallantern,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,creamcupidheartscoathanger,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,knittedunionflaghotwaterbottle,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,redwoollyhottiewhiteheart.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,packof20spaceboynapkins,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,children'saprondollygirl,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,childrenscutlerydollygirl,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,childrenscutlerycircusparade,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,bakingset9pieceretrospot,3,12/9/2011 12:50,4.95,12680.0,France

# Step 6: Filter for a Single Country (e.g., United Kingdom)

In [9]:
data[data['Country'] == 'United Kingdom']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,whitehangingheartt-lightholder,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,whitemetallantern,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,creamcupidheartscoathanger,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,knittedunionflaghotwaterbottle,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,redwoollyhottiewhiteheart.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541889,581585,22466,fairytalecottagenightlight,12,12/9/2011 12:31,1.95,15804.0,United Kingdom
541890,581586,22061,largecakestandhangingstrawbery,8,12/9/2011 12:49,2.95,13113.0,United Kingdom
541891,581586,23275,setof3hangingowlsolliebeak,24,12/9/2011 12:49,1.25,13113.0,United Kingdom
541892,581586,21217,redretrospotroundcaketins,24,12/9/2011 12:49,8.95,13113.0,United Kingdom
541893,581586,20685,doormatredretrospot,10,12/9/2011 12:49,7.08,13113.0,United Kingdom

# Step 7: Remove Duplicates

In [10]:
data.drop_duplicates()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,whitehangingheartt-lightholder,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,whitemetallantern,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,creamcupidheartscoathanger,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,knittedunionflaghotwaterbottle,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,redwoollyhottiewhiteheart.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,packof20spaceboynapkins,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,children'saprondollygirl,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,childrenscutlerydollygirl,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,childrenscutlerycircusparade,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,bakingset9pieceretrospot,3,12/9/2011 12:50,4.95,12680.0,France

# Step 8: Add TotalPrice column , TotalPrice = Quantity *  UnitPrice

In [11]:
secondData['TotalPrice'] = secondData['Quantity'] * secondData['UnitPrice']
secondData

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France,14.85

# Step 9 : Check for Top 10 Selling Products

In [12]:
# group = data.groupby('Description').count().sort_values(ascending= False,by=['Quantity']).head(10)
# group['Quantity']

secondData['Description'].value_counts().head(10)

Description
WHITE HANGING HEART T-LIGHT HOLDER    2369
REGENCY CAKESTAND 3 TIER              2200
JUMBO BAG RED RETROSPOT               2159
PARTY BUNTING                         1727
LUNCH BAG RED RETROSPOT               1638
ASSORTED COLOUR BIRD ORNAMENT         1501
SET OF 3 CAKE TINS PANTRY DESIGN      1473
PACK OF 72 RETROSPOT CAKE CASES       1385
LUNCH BAG  BLACK SKULL.               1350
NATURAL SLATE HEART CHALKBOARD        1280
Name: count, dtype: int64

# Step 10 : Identify Most Active Customers

In [13]:
# groupCustomer = data.groupby('CustomerID').count().sort_values(ascending= False,by=['Quantity']).head(10)
# groupCustomer['']

secondData['CustomerID'].value_counts().head(10)

CustomerID
17841.0    7983
14911.0    5903
14096.0    5128
12748.0    4642
14606.0    2782
15311.0    2491
14646.0    2085
13089.0    1857
13263.0    1677
14298.0    1640
Name: count, dtype: int64

# Step 11: Time-Based Analysis | Convert InvoiceDate to datetime and check popular months/hours.

In [ ]:
months = secondData['InvoiceDate'].str.split().str[0].str.split('/').str[0]

hours = secondData['InvoiceDate'].str.split().str[1].str.split(':').str[0]


months.plot(kind='bar',xlabel='Months')
plt.show()

TypeError: no numeric data to plot

# Step 12: Convert to Basket Format

Example
<table border="1">
    <thead>
        <tr>
            <th>Transaction</th>
            <th>Milk</th>
            <th>Bread</th>
            <th>Butter</th>
        </tr>
    </thead>
    <tbody>
        <tr><td>T1</td><td>1</td><td>1</td><td>1</td></tr>
        <tr><td>T2</td><td>0</td><td>1</td><td>1</td></tr>
        <tr><td>T3</td><td>1</td><td>0</td><td>0</td></tr>
        <tr><td>T4</td><td>1</td><td>1</td><td>0</td></tr>
        <tr><td>T5</td><td>0</td><td>1</td><td>1</td></tr>
    </tbody>
</table>

Description,*boombox ipod classic,*usb office mirror ball,10 colour spaceboy pen,12 coloured party balloons,12 daisy pegs in wood box,12 egg house painted wood,12 hanging eggs hand painted,12 ivory rose peg place settings,12 message cards with envelopes,12 pencil small tube woodland,...,zinc star t-light holder,zinc sweetheart soap dish,zinc sweetheart wire letter rack,zinc t-light holder star large,zinc t-light holder stars large,zinc t-light holder stars small,zinc top 2 door wooden shelf,zinc willie winkie candle stick,zinc wire kitchen organiser,zinc wire sweetheart letter tray
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536366,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536367,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536368,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536369,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581585,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
581586,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A563185,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A563186,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A563187,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Step:13 : Save Basket Format into CSV file